### ISSUE TITLE
It fails to build on Ubuntu 16.04 

### ISSUE THREAD

**Issue by trappedinspacetime** [luksan/kodos#8]
Hi,
First of all thank you for porting `kodos` to `qt-4`.
I downloaded the source zip and extracted it on desktop then I ran the following commands:

     /usr/lib/i386-linux-gnu/qt4/bin/qmake -project 
     /usr/lib/i386-linux-gnu/qt4/bin/qmake -makefile
     make 
I got the following error:

     /usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
     (.text+0x18): undefined reference to `main'
     collect2: error: ld returned 1 exit status

What's wrong with it?
Regards.

**Comment by trappedinspacetime** [comment]
I'm sorry that it's my ignorance, I just noticed that it already has a `makefile` so no need to recreate it again. I also thought it ported to `c++`, it's pyqt. 
Author can delete this issue.
